name: "@soasme"
description: "Lin Ju's Blog"
meta_description: "Geek stuff."
url: "http://www.soasme.com"
author: "soasme"

logo: false
paginate: 15
baseurl: "/"
permalink: "/:year/:month/:day/:title"
domain_name: "http://www.soasme.com"
google_analytics: 'UA-36183732-1'

gems: 
  - jekyll-paginate
  - jekyll-feed

feed:
  path: feed/index.xml
